messages:
  no-perm: '&e&lWMR &7You do not have permission for this'
  only-in-game: '&e&lWMR &7You must be a player to use this command'
  create-usage: '&e&lWMR &7/wmr create &a<name>'
  delete-usage: '&e&lWMR &7/wmr delete &a<name>'
  setblocks-usage: '&e&lWMR &7/wmr setblocks &a<mine>'
  mine-already-exists: '&e&lWMR &7Mine named &a%mine% &7already exists'
  invalid-mine-name: '&e&lWMR &7This mine name is not valid'
  set-delay-and-content: '&e&lWMR &7Set delay and the block content of the mine'
  mine-not-found: '&e&lWMR &7The mine with that name could not be found'
  set-delay-usage: '&e&lWMR &7/wmr setdelay &a<mine> <delay>'
  invalid-number: '&e&lWMR &7This is not a valid number'
  mine-delay-set: '&e&lWMR &7Delay of &a%mine% &7is set to &a%delay%'
  entered-edit-mode: '&e&lWMR &7Now place the blocks of the mine, type &edone &7to quit'
  quit-edit-mode: '&e&lWMR &7Quit from edit mode'
  noblockplaced: '&e&lWMR &7Done, no block placed'
  blocks-saved: '&e&lWMR &7Blocks of &a%mine% &7saved!'
  invalid-sound: '&e&lWMR &7Invalid sound'
  sound-set: '&e&lWMR &7Sound &a%sound% &7is set for &a%mine%'
  invalid-effect: '&e&lWMR &7Invalid effect'
  effect-set: '&e&lWMR &a%effect% &7is set for &a%mine%'
  set-sound-usage: '&e&lWMR &7/wmr setsound <mine> <sound>'
  set-effect-usage: '&e&lWMR &7/wmr seteffect <mine> <effect>'
  set-content-usage: '&e&lWMR &7/wmr setcontent &a<mine>'
  commands:
    - '&e&lWMR &7by #fb220bt#fb390fh#fc4f13e#fc6616l#fc7c1ae#fc931eg#fda922e#fdc025n#fdd629d'
    - '&7/wmr create &a<mine>'
    - '&fTo create a mine'
    - '&7/wmr setdelay &a<mine> <delay>'
    - '&fTo set the delay of the mine'
    - '&7/wmr setcontent &a<mine>'
    - '&fTo enter edit mode for a mine'
    - '&7/wmr setsound &a<mine> <sound>'
    - '&fTo set the sound when breaking that mines'' blocks'
    - '&7/wmr seteffect &a<mine> <effect>'
    - '&fTo set an effect mine blocks'
  after-creation:
    - '&e&lWMR &7Mine named &a%mine% &7is created!'
    - '&7You need to set the content of the mine and its delay'
    - '&7To save and activate it!'
    - ' '
    - '&d/wmr setdelay <mine> <delay>'
    - '&d/wmr setcontent <mine>'