name: WMR
version: 1.0
api-version: 1.13
author: thelegend
website: mc-marketi.com
main: tr.thelegend.wminereset.WMR
commands:
  wmr:
    description: Main command
    aliases:
      - weirdminereset
      - wminereset
permissions:
  wmr.create:
    description: Perm to create mines
    default: op
  wmr.setdelay:
    description: Perm to set delay for the mines
    default: op
  wmr.setcontent:
    description: Perm to set content of a mine
    default: op
  wmr.mine:
    description: Perm to mine mines
    default: true
  wmr.setsound:
    description: Perm to set sounds
    default: op
  wmr.setbreakeffect:
    description: Perm to set break effects
    default: op
  wmr.setrefilleffect:
    description: Perm to set refill effect
    default: op